# Generated by Django 4.2 on 2023-04-13 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Kod')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Endirim faizi', max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodeUsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='promocodesuses', to='core.promocode', verbose_name='Promo kodu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='promocodeuses', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
        ),
    ]
