# Generated by Django 4.2 on 2023-04-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_promocode_promocodeusing'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='can_use_as_requested_until_deadline',
            field=models.BooleanField(default=True, help_text='Bitmə tarixinə qədər istəndiyi qədər istifadə edilə bilər?', verbose_name='Can use as requested until deadline'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='number_of_per_user',
            field=models.IntegerField(default=1, help_text='Hər bir istifadəçi neçə dəfə istifadə edə bilər?', verbose_name='Number of per user'),
        ),
    ]
