# Generated by Django 4.2 on 2023-04-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_promocode_can_use_as_requested_until_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocodeusing',
            name='promocode',
        ),
        migrations.RemoveField(
            model_name='promocodeusing',
            name='user',
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.DeleteModel(
            name='PromoCodeUsing',
        ),
    ]
