# Generated by Django 4.2 on 2023-04-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_applicant_promo_code_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='promo_code',
            field=models.CharField(blank=True, db_index=True, help_text='Promo Kod', max_length=6, null=True),
        ),
    ]
