# Generated by Django 4.2 on 2023-04-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_applicant_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
