# Generated by Django 4.2 on 2023-04-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_applicant_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycategory',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='Kategoriya', max_length=200, null=True, verbose_name='Category name'),
        ),
    ]
