# Generated by Django 4.2 on 2023-04-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='promo_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
