# Generated by Django 4.2 on 2023-04-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='promo_code',
        ),
    ]
