# Generated by Django 4.2 on 2023-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_myuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/Cool-Profile-Picture.webp', null=True, upload_to='profile_images'),
        ),
    ]
